/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Sdfasdf } from "./Sdfasdf";
import { SdfasdfCountArgs } from "./SdfasdfCountArgs";
import { SdfasdfFindManyArgs } from "./SdfasdfFindManyArgs";
import { SdfasdfFindUniqueArgs } from "./SdfasdfFindUniqueArgs";
import { DeleteSdfasdfArgs } from "./DeleteSdfasdfArgs";
import { SdfasdfService } from "../sdfasdf.service";
@graphql.Resolver(() => Sdfasdf)
export class SdfasdfResolverBase {
  constructor(protected readonly service: SdfasdfService) {}

  async _sdfasdfsMeta(
    @graphql.Args() args: SdfasdfCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Sdfasdf])
  async sdfasdfs(
    @graphql.Args() args: SdfasdfFindManyArgs
  ): Promise<Sdfasdf[]> {
    return this.service.sdfasdfs(args);
  }

  @graphql.Query(() => Sdfasdf, { nullable: true })
  async sdfasdf(
    @graphql.Args() args: SdfasdfFindUniqueArgs
  ): Promise<Sdfasdf | null> {
    const result = await this.service.sdfasdf(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Sdfasdf)
  async deleteSdfasdf(
    @graphql.Args() args: DeleteSdfasdfArgs
  ): Promise<Sdfasdf | null> {
    try {
      return await this.service.deleteSdfasdf(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
